services:
  fair-data-schema-api:
    image: dartfx/fair-data-schema-api:latest
    container_name: fair-data-schema-api
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - API_ROOT_PATH=${API_ROOT_PATH:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/status"]
      interval: 30s
      timeout: 5s
      retries: 3
